#!/usr/bin/env python3
"""
Agent Compiler - Generates complete agent code from parsed instructions.
"""

import os
import ast
import json
from pathlib import Path
from typing import Dict, List, Any, Optional
from datetime import datetime

class AgentCompiler:
    """
    Compiles agents from parsed instruction data.
    """
    
    def __init__(self, output_dir: str = "~/PROMETHEUS/output/generated_code/agents"):
        """
        Initialize the agent compiler.
        
        Args:
            output_dir: Directory for generated agent code.
        """
        self.output_dir = Path(output_dir).expanduser()
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def compile_agent(self, agent_data: Dict) -> Path:
        """
        Compile an agent definition into a complete Python module.
        
        Args:
            agent_data: Agent definition from parsed instructions.
            
        Returns:
            Path to the generated agent file.
        """
        agent_name = agent_data['name'].lower().replace(' ', '_')
        file_path = self.output_dir / f"{agent_name}.py"
        
        # Generate the agent code
        code = self._generate_agent_code(agent_data)
        
        # Validate the generated code
        try:
            ast.parse(code)
        except SyntaxError as e:
            raise ValueError(f"Generated agent code has syntax error: {e}")
        
        # Write the code
        with open(file_path, 'w') as f:
            f.write(code)
        
        return file_path
    
    def _generate_agent_code(self, agent_data: Dict) -> str:
        """
        Generate complete agent code from definition.
        
        Args:
            agent_data: Agent definition.
            
        Returns:
            Complete Python code for the agent.
        """
        name = agent_data['name']
        description = agent_data.get('description', f'Agent: {name}')
        inputs = agent_data.get('inputs', [])
        outputs = agent_data.get('outputs', [])
        provided_code = agent_data.get('code', '')
        source_file = agent_data.get('source_file', 'unknown')
        
        # Generate the agent class
        code = f'''"""
Agent: {name}
Generated by CAIS Autopoietic Compiler
Source: {source_file}
Generated: {datetime.now().isoformat()}
"""

import asyncio
import logging
from typing import Dict, Any, Optional
from datetime import datetime

logger = logging.getLogger(__name__)


class {name}:
    """
    {description}
    
    Inputs: {inputs}
    Outputs: {outputs}
    """
    
    def __init__(self):
        self.name = "{name}"
        self.description = "{description}"
        self.inputs = {inputs}
        self.outputs = {outputs}
        self.version = "1.0.0"
        self.execution_history = []
    
    async def execute(self, context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute the agent with the given context.
        
        Args:
            context: Execution context containing inputs and state.
            
        Returns:
            Dict containing outputs and execution results.
        """
        logger.info(f"Executing agent: {self.name}")
        
        try:
            # Validate inputs
            if not self._validate_inputs(context):
                return self._error_response("Input validation failed")
            
            # Prepare execution
            inputs = self._extract_inputs(context)
            
            # Execute the agent logic
            start_time = datetime.now()
            result = await self._execute_agent(inputs, context)
            execution_time = (datetime.now() - start_time).total_seconds()
            
            # Validate outputs
            if not self._validate_outputs(result):
                return self._error_response("Output validation failed")
            
            # Record execution
            self.execution_history.append({{
                'timestamp': datetime.now().isoformat(),
                'input': inputs,
                'output': result,
                'execution_time_seconds': execution_time
            }})
            
            return {{
                'agent': self.name,
                'status': 'success',
                'output': result,
                'execution_time': execution_time
            }}
            
        except Exception as e:
            logger.error(f"Agent {self.name} execution failed: {{e}}")
            return self._error_response(str(e))
    
    async def _execute_agent(self, inputs: Dict[str, Any], context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute the main agent logic.
        """
        # Default implementation
        logger.warning(f"Agent {self.name} has no custom implementation")
        return {{
            'message': f"Agent {self.name} executed with default implementation"
        }}
    
    def _validate_inputs(self, context: Dict[str, Any]) -> bool:
        """
        Validate that all required inputs are present.
        
        Args:
            context: Execution context.
            
        Returns:
            True if all inputs are valid.
        """
        for input_field in self.inputs:
            if input_field not in context:
                logger.error(f"Missing required input: {input_field}")
                return False
        return True
    
    def _validate_outputs(self, result: Dict[str, Any]) -> bool:
        """
        Validate that all required outputs are present.
        
        Args:
            result: Agent execution result.
            
        Returns:
            True if all outputs are present.
        """
        for output_field in self.outputs:
            if output_field not in result:
                logger.warning(f"Missing output: {output_field}")
        return True
    
    def _extract_inputs(self, context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Extract inputs from the context.
        
        Args:
            context: Execution context.
            
        Returns:
            Dict containing the extracted inputs.
        """
        return {{
            field: context.get(field)
            for field in self.inputs
        }}
    
    def _error_response(self, message: str) -> Dict[str, Any]:
        """
        Generate an error response.
        
        Args:
            message: Error message.
            
        Returns:
            Dict containing error information.
        """
        return {{
            'agent': self.name,
            'status': 'error',
            'error': message,
            'timestamp': datetime.now().isoformat()
        }}
    
    def get_history(self) -> List[Dict[str, Any]]:
        """
        Get the execution history of this agent.
        
        Returns:
            List of execution records.
        """
        return self.execution_history
    
    def to_dict(self) -> Dict[str, Any]:
        """
        Convert agent to dictionary.
        
        Returns:
            Dict containing agent information.
        """
        return {{
            'name': self.name,
            'description': self.description,
            'inputs': self.inputs,
            'outputs': self.outputs,
            'version': self.version,
            'execution_count': len(self.execution_history)
        }}
'''
        
        return code
