"""
Asynchronous WORM (Write‑Once‑Read‑Many) Ledger service.

Provides immutable forensic logging with cryptographic integrity verification.
"""

import hashlib
import json
import logging
import uuid
from datetime import datetime
from typing import Any, Dict, List, Optional

from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.models import WORMLedgerEntry

logger = logging.getLogger(__name__)


class ImmutableLedgerException(Exception):
    """Raised when an update or delete is attempted on the WORM Ledger."""
    pass


class WORMService:
    """
    Service for interacting with the immutable WORM Ledger.

    All write operations are append‑only. Updates and deletes are strictly
    forbidden. Provides cryptographic verification of stored entries.
    """

    def __init__(self, async_session_factory):
        """
        Initialise the service with an async session factory.

        Args:
            async_session_factory: A callable that returns an AsyncSession
                                   (e.g., async_sessionmaker).
        """
        self._session_factory = async_session_factory

    @staticmethod
    def _compute_hash(evidence_uri: str, violation_codes: Dict[str, Any]) -> str:
        """
        Compute a SHA‑256 hash deterministically from the evidence URI and violations.

        The payload is serialised with sorted keys to ensure reproducibility.

        Args:
            evidence_uri: GCS URI of the evidence.
            violation_codes: Structured violation data.

        Returns:
            Hexadecimal digest of the SHA‑256 hash.
        """
        # Serialise violation_codes deterministically
        violation_json = json.dumps(violation_codes, sort_keys=True, separators=(",", ":"))
        # Combine fields
        payload = f"{evidence_uri}|{violation_json}"
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()

    async def add_entry(
        self,
        evidence_gcs_uri: str,
        violation_codes: Dict[str, Any],
        *,
        extra_metadata: Optional[Dict[str, Any]] = None,
    ) -> WORMLedgerEntry:
        """
        Insert a new immutable entry into the WORM Ledger.

        The cryptographic hash is computed from the evidence URI and violation codes.
        Extra metadata is included in the hash if provided.

        Args:
            evidence_gcs_uri: GCS URI of the evidence (e.g., plan screenshot).
            violation_codes: The matched building codes (as a dict).
            extra_metadata: Optional additional context to be included in the hash
                            (but not stored directly).

        Returns:
            The newly created WORMLedgerEntry instance.

        Raises:
            RuntimeError: If database insertion fails.
        """
        # Compute hash, optionally including extra metadata
        hash_payload = violation_codes.copy()
        if extra_metadata:
            hash_payload["_extra"] = extra_metadata
        hash_value = self._compute_hash(evidence_gcs_uri, hash_payload)

        # Create ORM object (timestamp is auto-generated by database default)
        new_entry = WORMLedgerEntry(
            evidence_gcs_uri=evidence_gcs_uri,
            violation_codes=violation_codes,
            cryptographic_hash=hash_value,
        )

        async with self._session_factory() as session:
            session.add(new_entry)
            try:
                await session.commit()
                await session.refresh(new_entry)
            except Exception as e:
                await session.rollback()
                logger.exception("Failed to insert WORM entry")
                raise RuntimeError(f"Database insertion failed: {e}")

        logger.info("WORM entry created with ID: %s", new_entry.id)
        return new_entry

    async def get_entry(self, entry_id: uuid.UUID) -> Optional[WORMLedgerEntry]:
        """
        Retrieve a single entry by its UUID.

        Args:
            entry_id: The UUID of the entry.

        Returns:
            The WORMLedgerEntry instance, or None if not found.
        """
        async with self._session_factory() as session:
            return await session.get(WORMLedgerEntry, entry_id)

    async def get_all_entries(
        self, limit: int = 100, offset: int = 0
    ) -> List[WORMLedgerEntry]:
        """
        Retrieve a paginated list of all entries (ordered by timestamp descending).

        Args:
            limit: Maximum number of entries to return.
            offset: Number of entries to skip.

        Returns:
            List of WORMLedgerEntry instances.
        """
        stmt = (
            select(WORMLedgerEntry)
            .order_by(WORMLedgerEntry.timestamp.desc())
            .offset(offset)
            .limit(limit)
        )
        async with self._session_factory() as session:
            result = await session.execute(stmt)
            return result.scalars().all()

    async def verify_entry(self, entry: WORMLedgerEntry) -> bool:
        """
        Verify the cryptographic hash of a single entry.

        Recomputes the hash from the stored evidence URI and violation codes,
        and compares it with the stored hash.

        Args:
            entry: The entry to verify.

        Returns:
            True if the hash matches, False otherwise.
        """
        # Recompute hash using stored fields
        recomputed_hash = self._compute_hash(entry.evidence_gcs_uri, entry.violation_codes)
        return recomputed_hash == entry.cryptographic_hash

    async def verify_chain(self) -> Dict[str, Any]:
        """
        Verify the integrity of the entire WORM ledger.

        Iterates over all entries, recomputes their hashes, and checks for
        consistency. Also optionally checks that entries are in chronological
        order (if required).

        Returns:
            A dictionary with:
                - "valid": bool, True if all entries are valid.
                - "invalid_entries": list of entry IDs that failed verification.
                - "total": total number of entries checked.
        """
        async with self._session_factory() as session:
            # Fetch all entries ordered by timestamp ascending
            stmt = select(WORMLedgerEntry).order_by(WORMLedgerEntry.timestamp.asc())
            result = await session.execute(stmt)
            entries = result.scalars().all()

        invalid_ids = []
        for entry in entries:
            if not await self.verify_entry(entry):
                invalid_ids.append(str(entry.id))

        return {
            "valid": len(invalid_ids) == 0,
            "invalid_entries": invalid_ids,
            "total": len(entries),
        }

    # --- Forbidden operations ---

    async def update_entry(self, entry_id: uuid.UUID, **kwargs) -> None:
        """
        Update an entry – THIS IS FORBIDDEN.

        Raises:
            ImmutableLedgerException: Always.
        """
        raise ImmutableLedgerException(
            "WORM Ledger entries cannot be updated. Append‑only semantics enforced."
        )

    async def delete_entry(self, entry_id: uuid.UUID) -> None:
        """
        Delete an entry – THIS IS FORBIDDEN.

        Raises:
            ImmutableLedgerException: Always.
        """
        raise ImmutableLedgerException(
            "WORM Ledger entries cannot be deleted. Append‑only semantics enforced."
        )
